name: Waka Readme

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches: 
      - master

jobs:
  update-readme:
    name: Update README with metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_COMMIT: "False"
          SHOW_DAYS_OF_WEEK: "False"
          SHOW_PROJECTS: "False"
          SHOW_TIMEZONE: "False"
